@baseUrl = https://localhost:5232



### PERSON

### 🟢 GET - Listar todas as pessoas
GET {{baseUrl}}/api/Person
Accept: application/json



### 🔵 POST - Criar nova pessoa
POST {{baseUrl}}/api/Person
Content-Type: application/json

{
  "idPerson": 1,
  "name": "Leo",
  "email": "leonardo@email.com",
  "password": "123456",
  "role": "Admin"
}



### 🟡 GET - Obter pessoa por ID
GET {{baseUrl}}/api/Person/1
Accept: application/json



### 🟠 PUT - Atualizar pessoa por ID
PUT {{baseUrl}}/api/Person/1
Content-Type: application/json

{
  "idPerson": 1,
  "name": "Leonardo",
  "email": "leonardo@email.com",
  "password": "654321",
  "role": "Admin"
}



### 🔴 DELETE - Remover pessoa por ID
DELETE {{baseUrl}}/api/Person/1
Accept: application/json


### REVIEW


### 🟢 GET - Listar todas as reviews
GET {{baseUrl}}/api/Review
Accept: application/json



### 🔵 POST - Criar nova review
POST {{baseUrl}}/api/Review
Content-Type: application/json

{
  "idReading": 1,
  "description": "Estou feliz"
}



### 🟡 GET - Obter review por ID
GET {{baseUrl}}/api/Review/1
Accept: application/json



### 🟠 PUT - Atualizar review por ID
PUT {{baseUrl}}/api/Review/1
Content-Type: application/json

{
  "idReading": 1,
  "description": "Estou triste"
}



### 🔴 DELETE - Remover review por ID
DELETE {{baseUrl}}/api/Review/1
Accept: application/json


### AUTH (LOGIN)


### 🔐 POST - Login (gerar token JWT)
POST {{baseUrl}}/api/Auth/login
Content-Type: application/json

{
  "email": "leonardo@email.com",
  "password": "123456"
}
